#!/usr/bin/env bash

echo "Generating ssh-agent-mux.rb cask file..."

VERSION="${VERSION:-${GITHUB_REF##*/}}"

SHA_DARWIN_ARM64="$(sha256sum artifacts/archives/ssh-agent-mux_darwin_arm64.tar.gz | awk '{print $1}')"
SHA_LINUX_AMD64="$(sha256sum artifacts/archives/ssh-agent-mux_linux_amd64.tar.gz | awk '{print $1}')"
SHA_LINUX_ARM64="$(sha256sum artifacts/archives/ssh-agent-mux_linux_arm64.tar.gz | awk '{print $1}')"

tee "ssh-agent-mux.rb" << EOF
# This file was generated by generate-cask.sh. DO NOT EDIT.
cask "ssh-agent-mux" do
  name "ssh-agent-mux"
  desc "SSH Agent Multiplexer"
  homepage "https://github.com/na4ma4/ssh-agent-mux"
  version "${VERSION}"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-agent-mux"

  on_macos do
    on_arm do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/v#{version}/ssh-agent-mux_darwin_arm64.tar.gz"
      sha256 "${SHA_DARWIN_ARM64}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/v#{version}/ssh-agent-mux_linux_amd64.tar.gz"
      sha256 "${SHA_LINUX_AMD64}"
    end
    on_arm do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/v#{version}/ssh-agent-mux_linux_arm64.tar.gz"
      sha256 "${SHA_LINUX_ARM64}"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssh-agent-mux"]
    end
  end

  # No zap stanza required
end
EOF

echo "Generated ssh-agent-mux.rb"
