# This file was generated by generate-cask.sh. DO NOT EDIT.
cask "ssh-agent-mux" do
  name "ssh-agent-mux"
  desc "SSH Agent Multiplexer"
  homepage "https://github.com/na4ma4/ssh-agent-mux"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-agent-mux"

  on_macos do
    on_arm do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/#{version}/ssh-agent-mux_darwin_arm64.tar.gz"
      sha256 "f510f45198d2a34ca91c5a2eaef87c80b42712fa09c9e258450878bc5060b87c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/#{version}/ssh-agent-mux_linux_amd64.tar.gz"
      sha256 "e51c6a49545ba923867cee0c201a358450c5bf4f8b5ad9a44c399feea1e3465e"
    end
    on_arm do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/#{version}/ssh-agent-mux_linux_arm64.tar.gz"
      sha256 "8ddcf718d15ae480fe01f0671555f1ade463af3ace243b40083800bcd168e330"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssh-agent-mux"]
    end
  end

  # No zap stanza required
end
