// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: github.com/na4ma4/ssh-agent-mux/api/commands.proto

package api

import (
	go_cliversion "github.com/dosquad/go-cliversion"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines commands for communicating with ssh-agent-mux daemon
type Config struct {
	state                        protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Id                *string                    `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Ts                *timestamppb.Timestamp     `protobuf:"bytes,2,opt,name=ts"`
	xxx_hidden_SocketPath        *string                    `protobuf:"bytes,10,opt,name=socket_path,json=socketPath"`
	xxx_hidden_BackendSocketPath []string                   `protobuf:"bytes,11,rep,name=backend_socket_path,json=backendSocketPath"`
	xxx_hidden_Pid               int64                      `protobuf:"varint,12,opt,name=pid"`
	xxx_hidden_StartTime         *timestamppb.Timestamp     `protobuf:"bytes,13,opt,name=start_time,json=startTime"`
	xxx_hidden_Version           *string                    `protobuf:"bytes,100,opt,name=version"`
	xxx_hidden_VersionInfo       *go_cliversion.VersionInfo `protobuf:"bytes,101,opt,name=version_info,json=versionInfo"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Config) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Config) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Ts
	}
	return nil
}

func (x *Config) GetSocketPath() string {
	if x != nil {
		if x.xxx_hidden_SocketPath != nil {
			return *x.xxx_hidden_SocketPath
		}
		return ""
	}
	return ""
}

func (x *Config) GetBackendSocketPath() []string {
	if x != nil {
		return x.xxx_hidden_BackendSocketPath
	}
	return nil
}

func (x *Config) GetPid() int64 {
	if x != nil {
		return x.xxx_hidden_Pid
	}
	return 0
}

func (x *Config) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartTime
	}
	return nil
}

func (x *Config) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *Config) GetVersionInfo() *go_cliversion.VersionInfo {
	if x != nil {
		return x.xxx_hidden_VersionInfo
	}
	return nil
}

func (x *Config) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *Config) SetTs(v *timestamppb.Timestamp) {
	x.xxx_hidden_Ts = v
}

func (x *Config) SetSocketPath(v string) {
	x.xxx_hidden_SocketPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *Config) SetBackendSocketPath(v []string) {
	x.xxx_hidden_BackendSocketPath = v
}

func (x *Config) SetPid(v int64) {
	x.xxx_hidden_Pid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *Config) SetStartTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartTime = v
}

func (x *Config) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *Config) SetVersionInfo(v *go_cliversion.VersionInfo) {
	x.xxx_hidden_VersionInfo = v
}

func (x *Config) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Config) HasTs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ts != nil
}

func (x *Config) HasSocketPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Config) HasPid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Config) HasStartTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartTime != nil
}

func (x *Config) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Config) HasVersionInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_VersionInfo != nil
}

func (x *Config) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Config) ClearTs() {
	x.xxx_hidden_Ts = nil
}

func (x *Config) ClearSocketPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SocketPath = nil
}

func (x *Config) ClearPid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Pid = 0
}

func (x *Config) ClearStartTime() {
	x.xxx_hidden_StartTime = nil
}

func (x *Config) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Version = nil
}

func (x *Config) ClearVersionInfo() {
	x.xxx_hidden_VersionInfo = nil
}

type Config_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                *string
	Ts                *timestamppb.Timestamp
	SocketPath        *string
	BackendSocketPath []string
	Pid               *int64
	StartTime         *timestamppb.Timestamp
	Version           *string
	VersionInfo       *go_cliversion.VersionInfo
}

func (b0 Config_builder) Build() *Config {
	m0 := &Config{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Ts = b.Ts
	if b.SocketPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_SocketPath = b.SocketPath
	}
	x.xxx_hidden_BackendSocketPath = b.BackendSocketPath
	if b.Pid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Pid = *b.Pid
	}
	x.xxx_hidden_StartTime = b.StartTime
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_Version = b.Version
	}
	x.xxx_hidden_VersionInfo = b.VersionInfo
	return m0
}

// Ping/Pong commands for health checking
type Ping struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Ts          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Ping) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Ping) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Ts
	}
	return nil
}

func (x *Ping) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Ping) SetTs(v *timestamppb.Timestamp) {
	x.xxx_hidden_Ts = v
}

func (x *Ping) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Ping) HasTs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ts != nil
}

func (x *Ping) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Ping) ClearTs() {
	x.xxx_hidden_Ts = nil
}

type Ping_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
	Ts *timestamppb.Timestamp
}

func (b0 Ping_builder) Build() *Ping {
	m0 := &Ping{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Ts = b.Ts
	return m0
}

// Pong response to Ping
type Pong struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Ts          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts"`
	xxx_hidden_PingTs      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ping_ts,json=pingTs"`
	xxx_hidden_StartTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime"`
	xxx_hidden_Pid         int64                  `protobuf:"varint,10,opt,name=pid"`
	xxx_hidden_Version     *string                `protobuf:"bytes,11,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Pong) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Pong) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Ts
	}
	return nil
}

func (x *Pong) GetPingTs() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_PingTs
	}
	return nil
}

func (x *Pong) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartTime
	}
	return nil
}

func (x *Pong) GetPid() int64 {
	if x != nil {
		return x.xxx_hidden_Pid
	}
	return 0
}

func (x *Pong) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *Pong) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *Pong) SetTs(v *timestamppb.Timestamp) {
	x.xxx_hidden_Ts = v
}

func (x *Pong) SetPingTs(v *timestamppb.Timestamp) {
	x.xxx_hidden_PingTs = v
}

func (x *Pong) SetStartTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartTime = v
}

func (x *Pong) SetPid(v int64) {
	x.xxx_hidden_Pid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *Pong) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *Pong) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Pong) HasTs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ts != nil
}

func (x *Pong) HasPingTs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PingTs != nil
}

func (x *Pong) HasStartTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartTime != nil
}

func (x *Pong) HasPid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Pong) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Pong) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Pong) ClearTs() {
	x.xxx_hidden_Ts = nil
}

func (x *Pong) ClearPingTs() {
	x.xxx_hidden_PingTs = nil
}

func (x *Pong) ClearStartTime() {
	x.xxx_hidden_StartTime = nil
}

func (x *Pong) ClearPid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Pid = 0
}

func (x *Pong) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Version = nil
}

type Pong_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        *string
	Ts        *timestamppb.Timestamp
	PingTs    *timestamppb.Timestamp
	StartTime *timestamppb.Timestamp
	Pid       *int64
	Version   *string
}

func (b0 Pong_builder) Build() *Pong {
	m0 := &Pong{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Ts = b.Ts
	x.xxx_hidden_PingTs = b.PingTs
	x.xxx_hidden_StartTime = b.StartTime
	if b.Pid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Pid = *b.Pid
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Version = b.Version
	}
	return m0
}

// Shutdown command to stop the daemon
type ShutdownRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Ts          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts"`
	xxx_hidden_Force       bool                   `protobuf:"varint,10,opt,name=force"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ShutdownRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *ShutdownRequest) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Ts
	}
	return nil
}

func (x *ShutdownRequest) GetForce() bool {
	if x != nil {
		return x.xxx_hidden_Force
	}
	return false
}

func (x *ShutdownRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ShutdownRequest) SetTs(v *timestamppb.Timestamp) {
	x.xxx_hidden_Ts = v
}

func (x *ShutdownRequest) SetForce(v bool) {
	x.xxx_hidden_Force = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ShutdownRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ShutdownRequest) HasTs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ts != nil
}

func (x *ShutdownRequest) HasForce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ShutdownRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *ShutdownRequest) ClearTs() {
	x.xxx_hidden_Ts = nil
}

func (x *ShutdownRequest) ClearForce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Force = false
}

type ShutdownRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id    *string
	Ts    *timestamppb.Timestamp
	Force *bool
}

func (b0 ShutdownRequest_builder) Build() *ShutdownRequest {
	m0 := &ShutdownRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Ts = b.Ts
	if b.Force != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Force = *b.Force
	}
	return m0
}

// Response to commands
type CommandResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Ts          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts"`
	xxx_hidden_Success     bool                   `protobuf:"varint,10,opt,name=success"`
	xxx_hidden_Message     *string                `protobuf:"bytes,11,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommandResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *CommandResponse) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Ts
	}
	return nil
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *CommandResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *CommandResponse) SetTs(v *timestamppb.Timestamp) {
	x.xxx_hidden_Ts = v
}

func (x *CommandResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *CommandResponse) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *CommandResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CommandResponse) HasTs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ts != nil
}

func (x *CommandResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CommandResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CommandResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *CommandResponse) ClearTs() {
	x.xxx_hidden_Ts = nil
}

func (x *CommandResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Success = false
}

func (x *CommandResponse) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Message = nil
}

type CommandResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *string
	Ts      *timestamppb.Timestamp
	Success *bool
	Message *string
}

func (b0 CommandResponse_builder) Build() *CommandResponse {
	m0 := &CommandResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Ts = b.Ts
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Success = *b.Success
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

// Request for configuration
type ConfigRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Ts          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *ConfigRequest) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Ts
	}
	return nil
}

func (x *ConfigRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ConfigRequest) SetTs(v *timestamppb.Timestamp) {
	x.xxx_hidden_Ts = v
}

func (x *ConfigRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConfigRequest) HasTs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ts != nil
}

func (x *ConfigRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *ConfigRequest) ClearTs() {
	x.xxx_hidden_Ts = nil
}

type ConfigRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
	Ts *timestamppb.Timestamp
}

func (b0 ConfigRequest_builder) Build() *ConfigRequest {
	m0 := &ConfigRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Ts = b.Ts
	return m0
}

var File_github_com_na4ma4_ssh_agent_mux_api_commands_proto protoreflect.FileDescriptor

const file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_rawDesc = "" +
	"\n" +
	"2github.com/na4ma4/ssh-agent-mux/api/commands.proto\x12\x0fsshagentmux.api\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.github.com/dosquad/go-cliversion/version.proto\"\xcc\x02\n" +
	"\x06Config\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x1f\n" +
	"\vsocket_path\x18\n" +
	" \x01(\tR\n" +
	"socketPath\x12.\n" +
	"\x13backend_socket_path\x18\v \x03(\tR\x11backendSocketPath\x12\x10\n" +
	"\x03pid\x18\f \x01(\x03R\x03pid\x129\n" +
	"\n" +
	"start_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x18\n" +
	"\aversion\x18d \x01(\tR\aversion\x12B\n" +
	"\fversion_info\x18e \x01(\v2\x1f.dosquad.cliversion.VersionInfoR\vversionInfoJ\x04\b\x03\x10\n" +
	"J\x04\b\x0e\x10d\"B\n" +
	"\x04Ping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\"\xe4\x01\n" +
	"\x04Pong\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x123\n" +
	"\aping_ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06pingTs\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x10\n" +
	"\x03pid\x18\n" +
	" \x01(\x03R\x03pid\x12\x18\n" +
	"\aversion\x18\v \x01(\tR\aversionJ\x04\b\x05\x10\n" +
	"\"i\n" +
	"\x0fShutdownRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x14\n" +
	"\x05force\x18\n" +
	" \x01(\bR\x05forceJ\x04\b\x03\x10\n" +
	"\"\x87\x01\n" +
	"\x0fCommandResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x18\n" +
	"\asuccess\x18\n" +
	" \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessageJ\x04\b\x03\x10\n" +
	"\"K\n" +
	"\rConfigRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02tsB-Z#github.com/na4ma4/ssh-agent-mux/api\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe9\a"

var file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_goTypes = []any{
	(*Config)(nil),                    // 0: sshagentmux.api.Config
	(*Ping)(nil),                      // 1: sshagentmux.api.Ping
	(*Pong)(nil),                      // 2: sshagentmux.api.Pong
	(*ShutdownRequest)(nil),           // 3: sshagentmux.api.ShutdownRequest
	(*CommandResponse)(nil),           // 4: sshagentmux.api.CommandResponse
	(*ConfigRequest)(nil),             // 5: sshagentmux.api.ConfigRequest
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
	(*go_cliversion.VersionInfo)(nil), // 7: dosquad.cliversion.VersionInfo
}
var file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_depIdxs = []int32{
	6,  // 0: sshagentmux.api.Config.ts:type_name -> google.protobuf.Timestamp
	6,  // 1: sshagentmux.api.Config.start_time:type_name -> google.protobuf.Timestamp
	7,  // 2: sshagentmux.api.Config.version_info:type_name -> dosquad.cliversion.VersionInfo
	6,  // 3: sshagentmux.api.Ping.ts:type_name -> google.protobuf.Timestamp
	6,  // 4: sshagentmux.api.Pong.ts:type_name -> google.protobuf.Timestamp
	6,  // 5: sshagentmux.api.Pong.ping_ts:type_name -> google.protobuf.Timestamp
	6,  // 6: sshagentmux.api.Pong.start_time:type_name -> google.protobuf.Timestamp
	6,  // 7: sshagentmux.api.ShutdownRequest.ts:type_name -> google.protobuf.Timestamp
	6,  // 8: sshagentmux.api.CommandResponse.ts:type_name -> google.protobuf.Timestamp
	6,  // 9: sshagentmux.api.ConfigRequest.ts:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_init() }
func file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_init() {
	if File_github_com_na4ma4_ssh_agent_mux_api_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_rawDesc), len(file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_goTypes,
		DependencyIndexes: file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_depIdxs,
		MessageInfos:      file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_msgTypes,
	}.Build()
	File_github_com_na4ma4_ssh_agent_mux_api_commands_proto = out.File
	file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_goTypes = nil
	file_github_com_na4ma4_ssh_agent_mux_api_commands_proto_depIdxs = nil
}
